cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

before_script:
  - npm ci --build-from-source

Unit tests:
  image: node:10
  script:
    - npm test
  coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'
