#!/usr/bin/env node

const solfege = require('solfegejs');
const TradingBot = require("./Bundle");

const application = solfege.factory(`${__dirname}/config/production.yml`);
application.addBundle(new TradingBot);

const parameters = process.argv.slice(2);
application.start(parameters);
