services:
  run_bot_command:
    class: commands/RunBot
    arguments:
      - "@container"
      - "%bots%"
    tags:
      - { name: "solfege.console.command" }

  candlestick_fetcher:
    class: services/CandlestickFetcher

  price_fetcher:
    class: services/PriceFetcher
    arguments:
      - "@candlestick_fetcher"

  exchange_factory:
    class: services/ExchangeFactory
    arguments:
      - "@price_fetcher"
      - "%exchanges%"

  # SIGNALS

  falseSignal:
    class: signals/False

  everyMinute:
    class: signals/EveryMinute

  macdCrossUp:
    class: signals/MacdCrossUp
    arguments:
      - "@candlestick_fetcher"

  macdCrossDown:
    class: signals/MacdCrossDown
    arguments:
      - "@candlestick_fetcher"

  # ENTRY STRATEGIES

  buyAtMarket:
    class: entryStrategies/BuyAtMarket
    arguments:
      - "@exchange_factory"

  # TAKE PROFIT STRATEGIES

  singleFactor:
    class: takeProfitStrategies/SingleFactor

